/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aipon_xsr;

/**
 *
 * @Author Jsven Dan Kawan-kawan (Billie, Juan)
 */

import java.awt.Desktop;
import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import jaco.mp3.player.MP3Player;
import java.io.File;

public class INTERFACE extends javax.swing.JFrame {

    /**
     * Creates new form INTERFACE
     */
    
    double num,ans;
    int perhitungan;
    
    public INTERFACE() {
        initComponents();
        
        Tombol_On.setEnabled(false);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    
    public static final String SONG = "song\\WIBU.mp3";
    MP3Player player = new MP3Player (new File(SONG));
    
    public void operasi_hitung()
    {
        switch (perhitungan)
        {
            case 1:
                ans = num + Double.parseDouble(Tempat_Angka.getText());
                Tempat_Angka.setText(Double.toString(ans));
                break;
                
            case 2:
                ans = num - Double.parseDouble(Tempat_Angka.getText());
                Tempat_Angka.setText(Double.toString(ans));
                break;
                
            case 3:
                ans = num * Double.parseDouble(Tempat_Angka.getText());
                Tempat_Angka.setText(Double.toString(ans));
                break;
                
            case 4:
                ans = num / Double.parseDouble(Tempat_Angka.getText());
                Tempat_Angka.setText(Double.toString(ans));
                break;    
        }    
    }
    
    public void off()
    {
        Tempat_Angka.setEnabled(false);
        
        Tombol_On.setEnabled(true);
        Tombol_Off.setEnabled(false);
        
        Angka_0.setEnabled(false);
        Angka_1.setEnabled(false);
        Angka_2.setEnabled(false);
        Angka_3.setEnabled(false);
        Angka_4.setEnabled(false);
        Angka_5.setEnabled(false);
        Angka_6.setEnabled(false);
        Angka_7.setEnabled(false);
        Angka_8.setEnabled(false);
        Angka_9.setEnabled(false);
        Hapus.setEnabled(false);
        Clear.setEnabled(false);
        Desimal.setEnabled(false);
        Kurang.setEnabled(false);
        Tambah.setEnabled(false);
        Perkalian.setEnabled(false);
        Pembagian.setEnabled(false);
        Hasil.setEnabled(false);
    }
    
    public void on()
    {
        Tempat_Angka.setEnabled(true);
        
        Tombol_On.setEnabled(false);
        Tombol_Off.setEnabled(true);
        
        Angka_0.setEnabled(true);
        Angka_1.setEnabled(true);
        Angka_2.setEnabled(true);
        Angka_3.setEnabled(true);
        Angka_4.setEnabled(true);
        Angka_5.setEnabled(true);
        Angka_6.setEnabled(true);
        Angka_7.setEnabled(true);
        Angka_8.setEnabled(true);
        Angka_9.setEnabled(true);
        Hapus.setEnabled(true);
        Clear.setEnabled(true);
        Desimal.setEnabled(true);
        Kurang.setEnabled(true);
        Tambah.setEnabled(true);
        Perkalian.setEnabled(true);
        Pembagian.setEnabled(true);
        Hasil.setEnabled(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Base = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        Calculator = new javax.swing.JButton();
        About = new javax.swing.JButton();
        Editor = new javax.swing.JButton();
        Media = new javax.swing.JButton();
        Animasi = new javax.swing.JLabel();
        Enable = new javax.swing.JButton();
        Disable = new javax.swing.JButton();
        Editor_panel = new javax.swing.JPanel();
        Resize = new javax.swing.JButton();
        Flip_Horizontal = new javax.swing.JButton();
        Flip_Vertical = new javax.swing.JButton();
        Grayscale = new javax.swing.JButton();
        Animasi_editor = new javax.swing.JLabel();
        Editgambar = new javax.swing.JLabel();
        BackbuttonEditor = new javax.swing.JButton();
        Calc_panel = new javax.swing.JPanel();
        Animasi_calc = new javax.swing.JLabel();
        Tempat_Angka = new javax.swing.JTextField();
        Angka_1 = new javax.swing.JButton();
        Tombol_On = new javax.swing.JRadioButton();
        History = new javax.swing.JLabel();
        Tombol_Off = new javax.swing.JRadioButton();
        Angka_2 = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Angka_7 = new javax.swing.JButton();
        Angka_8 = new javax.swing.JButton();
        Angka_9 = new javax.swing.JButton();
        Angka_3 = new javax.swing.JButton();
        Angka_4 = new javax.swing.JButton();
        Angka_5 = new javax.swing.JButton();
        Angka_6 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Angka_0 = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        Kurang = new javax.swing.JButton();
        Perkalian = new javax.swing.JButton();
        Pembagian = new javax.swing.JButton();
        Desimal = new javax.swing.JButton();
        Hasil = new javax.swing.JButton();
        BackbuttonCalc = new javax.swing.JButton();
        Media_panel = new javax.swing.JPanel();
        Animasi_media = new javax.swing.JLabel();
        Play_Music = new javax.swing.JButton();
        Play_Video = new javax.swing.JButton();
        BackbuttonMedia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retro_Device");
        setBackground(new java.awt.Color(191, 237, 242));

        Base.setBackground(new java.awt.Color(0, 0, 0));
        Base.setForeground(new java.awt.Color(191, 237, 242));
        Base.setToolTipText("");
        Base.setLayout(new java.awt.CardLayout());

        Welcome.setBackground(new java.awt.Color(0, 0, 0));
        Welcome.setPreferredSize(new java.awt.Dimension(513, 870));

        Calculator.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\calcButtons.png")); // NOI18N
        Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorActionPerformed(evt);
            }
        });

        About.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\aboutButtons.png")); // NOI18N
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        Editor.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\EditButtons.png")); // NOI18N
        Editor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorActionPerformed(evt);
            }
        });

        Media.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\MediaButtons.png")); // NOI18N
        Media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediaActionPerformed(evt);
            }
        });

        Enable.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\playButtons.png")); // NOI18N
        Enable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnableActionPerformed(evt);
            }
        });

        Disable.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\pauseButtons (1).png")); // NOI18N
        Disable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                        .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Media, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Editor, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                        .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Enable, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Disable, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(Animasi, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Animasi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Enable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Disable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(Media, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Editor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        Base.add(Welcome, "card2");

        Editor_panel.setBackground(new java.awt.Color(0, 0, 0));
        Editor_panel.setPreferredSize(new java.awt.Dimension(513, 870));

        Resize.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\resizeButtons.png")); // NOI18N
        Resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResizeActionPerformed(evt);
            }
        });

        Flip_Horizontal.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\verticalButtons.png")); // NOI18N
        Flip_Horizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Flip_HorizontalActionPerformed(evt);
            }
        });

        Flip_Vertical.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\horizonButtons.png")); // NOI18N
        Flip_Vertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Flip_VerticalActionPerformed(evt);
            }
        });

        Grayscale.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\GrayButtons.png")); // NOI18N
        Grayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayscaleActionPerformed(evt);
            }
        });

        Animasi_editor.setForeground(new java.awt.Color(240, 240, 240));

        Editgambar.setForeground(new java.awt.Color(240, 240, 240));

        BackbuttonEditor.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\backButtons.png")); // NOI18N
        BackbuttonEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonEditorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Editor_panelLayout = new javax.swing.GroupLayout(Editor_panel);
        Editor_panel.setLayout(Editor_panelLayout);
        Editor_panelLayout.setHorizontalGroup(
            Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Editor_panelLayout.createSequentialGroup()
                .addGroup(Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Editor_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackbuttonEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Editor_panelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Resize, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Flip_Vertical, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Grayscale, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Flip_Horizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Editor_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Editgambar, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(Animasi_editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
        );
        Editor_panelLayout.setVerticalGroup(
            Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Editor_panelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Animasi_editor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Editgambar, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Resize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Flip_Horizontal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Editor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Flip_Vertical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grayscale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(BackbuttonEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Base.add(Editor_panel, "card3");

        Calc_panel.setBackground(new java.awt.Color(0, 0, 0));
        Calc_panel.setPreferredSize(new java.awt.Dimension(513, 870));

        Animasi_calc.setForeground(new java.awt.Color(240, 240, 240));

        Tempat_Angka.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tempat_Angka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tempat_AngkaActionPerformed(evt);
            }
        });

        Angka_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\1Buttons (1).png")); // NOI18N
        Angka_1.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_1ActionPerformed(evt);
            }
        });

        Tombol_On.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Tombol_On);
        Tombol_On.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tombol_On.setForeground(new java.awt.Color(240, 240, 240));
        Tombol_On.setSelected(true);
        Tombol_On.setText("ON");
        Tombol_On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_OnActionPerformed(evt);
            }
        });

        History.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        History.setForeground(new java.awt.Color(240, 240, 240));

        Tombol_Off.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Tombol_Off);
        Tombol_Off.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tombol_Off.setForeground(new java.awt.Color(240, 240, 240));
        Tombol_Off.setText("OFF");
        Tombol_Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_OffActionPerformed(evt);
            }
        });

        Angka_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\2Buttons.png")); // NOI18N
        Angka_2.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_2ActionPerformed(evt);
            }
        });

        Hapus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Hapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\hapusButtons.png")); // NOI18N
        Hapus.setPreferredSize(new java.awt.Dimension(50, 50));
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Angka_7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\7Buttons.png")); // NOI18N
        Angka_7.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_7ActionPerformed(evt);
            }
        });

        Angka_8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\8Buttons.png")); // NOI18N
        Angka_8.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_8ActionPerformed(evt);
            }
        });

        Angka_9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\9Buttons.png")); // NOI18N
        Angka_9.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_9ActionPerformed(evt);
            }
        });

        Angka_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\3Buttons.png")); // NOI18N
        Angka_3.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_3ActionPerformed(evt);
            }
        });

        Angka_4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\4Buttons.png")); // NOI18N
        Angka_4.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_4ActionPerformed(evt);
            }
        });

        Angka_5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\5Buttons.png")); // NOI18N
        Angka_5.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_5ActionPerformed(evt);
            }
        });

        Angka_6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\6Buttons.png")); // NOI18N
        Angka_6.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_6ActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\clearButtons.png")); // NOI18N
        Clear.setPreferredSize(new java.awt.Dimension(50, 50));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Angka_0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Angka_0.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\0Buttons.png")); // NOI18N
        Angka_0.setPreferredSize(new java.awt.Dimension(50, 50));
        Angka_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka_0ActionPerformed(evt);
            }
        });

        Tambah.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Tambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\plusButtons.png")); // NOI18N
        Tambah.setPreferredSize(new java.awt.Dimension(50, 50));
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Kurang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Kurang.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\minusButtons.png")); // NOI18N
        Kurang.setPreferredSize(new java.awt.Dimension(50, 50));
        Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangActionPerformed(evt);
            }
        });

        Perkalian.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Perkalian.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\kaliButtons.png")); // NOI18N
        Perkalian.setPreferredSize(new java.awt.Dimension(50, 50));
        Perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerkalianActionPerformed(evt);
            }
        });

        Pembagian.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Pembagian.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\pembagianButtons.png")); // NOI18N
        Pembagian.setPreferredSize(new java.awt.Dimension(50, 50));
        Pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembagianActionPerformed(evt);
            }
        });

        Desimal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Desimal.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\decimalButtons.png")); // NOI18N
        Desimal.setPreferredSize(new java.awt.Dimension(50, 50));
        Desimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesimalActionPerformed(evt);
            }
        });

        Hasil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Hasil.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\hasilButtons.png")); // NOI18N
        Hasil.setPreferredSize(new java.awt.Dimension(50, 50));
        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });

        BackbuttonCalc.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\backButtons.png")); // NOI18N
        BackbuttonCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Calc_panelLayout = new javax.swing.GroupLayout(Calc_panel);
        Calc_panel.setLayout(Calc_panelLayout);
        Calc_panelLayout.setHorizontalGroup(
            Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Calc_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Animasi_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(Calc_panelLayout.createSequentialGroup()
                .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Angka_7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Angka_8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Angka_9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Angka_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Angka_5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Angka_6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Perkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Angka_1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Angka_2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(Angka_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(Angka_0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Desimal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BackbuttonCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tombol_On)
                            .addComponent(Tombol_Off))
                        .addGap(21, 21, 21)
                        .addComponent(Tempat_Angka, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Calc_panelLayout.setVerticalGroup(
            Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calc_panelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Animasi_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Tombol_On)
                        .addGap(15, 15, 15)
                        .addComponent(Tombol_Off))
                    .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(History, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tempat_Angka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Angka_7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Angka_8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Angka_9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Angka_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Angka_5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Angka_6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Perkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Angka_1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Angka_2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Angka_3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Calc_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calc_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Angka_0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Desimal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addComponent(BackbuttonCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Base.add(Calc_panel, "card4");

        Media_panel.setBackground(new java.awt.Color(0, 0, 0));
        Media_panel.setPreferredSize(new java.awt.Dimension(513, 870));

        Animasi_media.setForeground(new java.awt.Color(240, 240, 240));

        Play_Music.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\musicButtons.png")); // NOI18N
        Play_Music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Play_MusicActionPerformed(evt);
            }
        });

        Play_Video.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\videoButtons.png")); // NOI18N
        Play_Video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Play_VideoActionPerformed(evt);
            }
        });

        BackbuttonMedia.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\AIPON_XSR\\img\\backButtons.png")); // NOI18N
        BackbuttonMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Media_panelLayout = new javax.swing.GroupLayout(Media_panel);
        Media_panel.setLayout(Media_panelLayout);
        Media_panelLayout.setHorizontalGroup(
            Media_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Media_panelLayout.createSequentialGroup()
                .addGroup(Media_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Media_panelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Play_Music, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Play_Video, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Media_panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BackbuttonMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Media_panelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Animasi_media, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        Media_panelLayout.setVerticalGroup(
            Media_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Media_panelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Animasi_media, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addGroup(Media_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Play_Music, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Media_panelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Play_Video, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(302, 302, 302)
                .addComponent(BackbuttonMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Base.add(Media_panel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int a= 0;
    Icon a1=new ImageIcon("img\\1.gif");
    Icon a2=new ImageIcon("img\\2.gif");
    Icon a3=new ImageIcon("img\\3.gif");
    Icon a4=new ImageIcon("img\\4.gif");
    Icon a5=new ImageIcon("img\\5.gif");
    Icon a6=new ImageIcon("img\\6.gif");
    Icon a7=new ImageIcon("img\\7.gif");
    Icon a8=new ImageIcon("img\\8.gif");
    
    Timer time=new Timer(120,new ActionListener()
    {public void actionPerformed(ActionEvent e)
      {
          a++;
          switch(a)
          {
              case 1:
              {
                  Animasi.setIcon(a1);
                  break;
              }
              case 2:
              {
                  Animasi.setIcon(a2);
                  break;
              }
              case 3:
              {
                  Animasi.setIcon(a3);
                  break;
              }
              case 4:
              {
                  Animasi.setIcon(a4);
                  break;
              }
              case 5:
              {
                  Animasi.setIcon(a5);
                  break;
              }
              case 6:
              {
                  Animasi.setIcon(a6);
                  break;
              }
              case 7:
              {
                  Animasi.setIcon(a7);
                  break;
              }
              case 8:
              {
                  Animasi.setIcon(a8);
                  break;
              }
          }
        
          if (a == 8)
          {
              a=0;
          }
      }
        
    });
    
    
    int b= 0;
    Icon b1=new ImageIcon("img\\ELabel.png");
    Icon b2=new ImageIcon("img\\EDLabel.png");
    Icon b3=new ImageIcon("img\\EDILabel.png");
    Icon b4=new ImageIcon("img\\EDITLabel.png");
    Icon b5=new ImageIcon("img\\EDITOLabel.png");
    Icon b6=new ImageIcon("img\\EDITORLabel.png");
    
    Timer time_editor=new Timer(120,new ActionListener()
    {public void actionPerformed(ActionEvent e)
      {
          b++;
          switch(b)
          {
              case 1:
              {
                  Animasi_editor.setIcon(b1);
                  break;
              }
              case 2:
              {
                  Animasi_editor.setIcon(b2);
                  break;
              }
              case 3:
              {
                  Animasi_editor.setIcon(b3);
                  break;
              }
              case 4:
              {
                  Animasi_editor.setIcon(b4);
                  break;
              }
              case 5:
              {
                  Animasi_editor.setIcon(b5);
                  break;
              }
              case 6:
              {
                  Animasi_editor.setIcon(b6);
                  break;
              }
          }
        
          if (b == 6)
          {
              b=0;
          }
      }
        
    });
    
    
    int c= 0;
    Icon c1=new ImageIcon("img\\CLabel.png");
    Icon c2=new ImageIcon("img\\CALabel.png");
    Icon c3=new ImageIcon("img\\CALLabel.png");
    Icon c4=new ImageIcon("img\\CALCLabel.png");

    
    Timer time_calc=new Timer(120,new ActionListener()
    {public void actionPerformed(ActionEvent e)
      {
          c++;
          switch(c)
          {
              case 1:
              {
                  Animasi_calc.setIcon(c1);
                  break;
              }
              case 2:
              {
                  Animasi_calc.setIcon(c2);
                  break;
              }
              case 3:
              {
                  Animasi_calc.setIcon(c3);
                  break;
              }
              case 4:
              {
                  Animasi_calc.setIcon(c4);
                  break;
              }
              
          }
        
          if (c == 4)
          {
              c=0;
          }
      }
        
    });
    
    int d= 0;
    Icon d1=new ImageIcon("img\\MLabel.png");
    Icon d2=new ImageIcon("img\\MELabel.png");
    Icon d3=new ImageIcon("img\\MEDILabel.png");
    Icon d4=new ImageIcon("img\\MEDILabel.png");
    Icon d5=new ImageIcon("img\\MEDIALabel.png");
    
    Timer time_media=new Timer(120,new ActionListener()
    {public void actionPerformed(ActionEvent e)
      {
          d++;
          switch(d)
          {
              case 1:
              {
                  Animasi_media.setIcon(d1);
                  break;
              }
              case 2:
              {
                  Animasi_media.setIcon(d2);
                  break;
              }
              case 3:
              {
                  Animasi_media.setIcon(d3);
                  break;
              }
              case 4:
              {
                  Animasi_media.setIcon(d4);
                  break;
              }
              case 5:
              {
                  Animasi_media.setIcon(d5);
                  break;
              }
              
          }
        
          if (d == 5)
          {
              d=0;
          }
      }
        
    });
    
    private void Flip_VerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Flip_VerticalActionPerformed
        File jpgOriginal = new File("img\\PACMANLabel.png");
        File jpgFVER = new File("img\\PACMANLabelVERTICAL.png");
        flip(jpgOriginal, jpgFVER, FLIP_VERTICAL);
        Icon FVER= new ImageIcon("img\\PACMANLabelVERTICAL.png");
        Editgambar.setIcon(FVER);
    }//GEN-LAST:event_Flip_VerticalActionPerformed

    private void GrayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayscaleActionPerformed
        BufferedImage img= null;
        File file = null;
        file = new File("img\\PACMANLabel.png");
        
        try {
            img = ImageIO.read(file);
            int height= img.getHeight();
            int width = img.getWidth();
            
            System.out.println("tinggi"+height+"lebar"+width);
            
            for(int y=0;y<height; y++){
                
                for(int x=0;x<width; x++){
                    int p = img.getRGB(x,y);
                            
                    int a = (p>>24) &0xff;
                     int r = (p>>16 ) &0xff;
                     int g = (p>>8 ) &0xff;
                     int b = (p) &0xff;
                     
                     int avg = (r+g+b)/3;
                     
                     p=(a<<24)|(avg<<16)|(avg<<8)|(avg);
                     img.setRGB(x,y,p);
                }
            }
            
            file = new File("img\\PACMANLabelGRAYSCALE.png");
            ImageIO.write(img, "png", file);
            
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        Icon GRAY= new ImageIcon("img\\PACMANLabelGRAYSCALE.png");
        Editgambar.setIcon(GRAY);
        
    }//GEN-LAST:event_GrayscaleActionPerformed

    private void Tempat_AngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tempat_AngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tempat_AngkaActionPerformed

    private void Angka_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_5ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "5");
    }//GEN-LAST:event_Angka_5ActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        num = Double.parseDouble(Tempat_Angka.getText());
        perhitungan = 1;
        Tempat_Angka.setText("");
        History.setText(num + "+");
    }//GEN-LAST:event_TambahActionPerformed

    private void Angka_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_7ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "7");
    }//GEN-LAST:event_Angka_7ActionPerformed

    private void Angka_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_8ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "8");
    }//GEN-LAST:event_Angka_8ActionPerformed

    private void Angka_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_9ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "9");
    }//GEN-LAST:event_Angka_9ActionPerformed

    private void Angka_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_4ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "4");
    }//GEN-LAST:event_Angka_4ActionPerformed

    private void Angka_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_6ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "6");
    }//GEN-LAST:event_Angka_6ActionPerformed

    private void Angka_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_1ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "1");
    }//GEN-LAST:event_Angka_1ActionPerformed

    private void Angka_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_2ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "2");
    }//GEN-LAST:event_Angka_2ActionPerformed

    private void Angka_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_3ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "3");
    }//GEN-LAST:event_Angka_3ActionPerformed

    private void Angka_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka_0ActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + "0");
    }//GEN-LAST:event_Angka_0ActionPerformed

    private void DesimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesimalActionPerformed
        Tempat_Angka.setText(Tempat_Angka.getText() + ".");
    }//GEN-LAST:event_DesimalActionPerformed

    private void KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangActionPerformed
        num = Double.parseDouble(Tempat_Angka.getText());
        perhitungan = 2;
        Tempat_Angka.setText("");
        History.setText(num + "-");
    }//GEN-LAST:event_KurangActionPerformed

    private void PerkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerkalianActionPerformed
        num = Double.parseDouble(Tempat_Angka.getText());
        perhitungan = 3;
        Tempat_Angka.setText("");
        History.setText(num + "x");
    }//GEN-LAST:event_PerkalianActionPerformed

    private void PembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembagianActionPerformed
        num = Double.parseDouble(Tempat_Angka.getText());
        perhitungan = 4;
        Tempat_Angka.setText("");
        History.setText(num + "/");
    }//GEN-LAST:event_PembagianActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        operasi_hitung();
        History.setText("");
    }//GEN-LAST:event_HasilActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Tempat_Angka.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        int panjang_angka = Tempat_Angka.getText().length();
        int hapus_ang = Tempat_Angka.getText().length() - 1;
        String store_angka;
        
        if (panjang_angka > 0)
        {
            StringBuilder hapus = new StringBuilder(Tempat_Angka.getText());
            hapus.deleteCharAt(hapus_ang);
            store_angka = hapus.toString();
            Tempat_Angka.setText(store_angka);
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void Tombol_OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_OnActionPerformed
        on();
    }//GEN-LAST:event_Tombol_OnActionPerformed

    private void Tombol_OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_OffActionPerformed
        off();
    }//GEN-LAST:event_Tombol_OffActionPerformed

    private void EnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnableActionPerformed
        time.start();
    }//GEN-LAST:event_EnableActionPerformed

    private void DisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisableActionPerformed
        time.stop();
    }//GEN-LAST:event_DisableActionPerformed

    private void ResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResizeActionPerformed
        File jpgOriginal = new File("img\\PACMANLabel.png");
        File jpgResized = new File("img\\PACMANLabelRESIZED.png");
        try {
            resizeImage(jpgOriginal, jpgResized, 36, 33, "png");
        } catch (IOException ex) {
            Logger.getLogger(INTERFACE.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Icon RESIZE= new ImageIcon("img\\PACMANLabelRESIZED.png");
        Editgambar.setIcon(RESIZE);
    }//GEN-LAST:event_ResizeActionPerformed

    private void Flip_HorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Flip_HorizontalActionPerformed
        File jpgOriginal = new File("img\\PACMANLabel.png");
        File jpgFHOR = new File("img\\PACMANLabelHORIZONTAL.png");
        flip(jpgOriginal, jpgFHOR, FLIP_HORIZONTAL);
        Icon FHOR= new ImageIcon("img\\PACMANLabelHORIZONTAL.png");
        Editgambar.setIcon(FHOR);
    }//GEN-LAST:event_Flip_HorizontalActionPerformed

    private void Play_MusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Play_MusicActionPerformed
        player.play();
    }//GEN-LAST:event_Play_MusicActionPerformed

    private void Play_VideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Play_VideoActionPerformed
        try {
            Desktop.getDesktop().open(new File("slap.mp4"));
        } catch (IOException ex) {
            Logger.getLogger(INTERFACE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Play_VideoActionPerformed

    private void MediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediaActionPerformed
        Base.removeAll();
        Base.repaint();
        Base.revalidate();
        
        Base.add(Media_panel);
        Base.repaint();
        Base.revalidate();
        time_media.start();
        
    }//GEN-LAST:event_MediaActionPerformed

    private void EditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorActionPerformed
        Base.removeAll();
        Base.repaint();
        Base.revalidate();
        
        Base.add(Editor_panel);
        Base.repaint();
        Base.revalidate();
        time_editor.start();
        Icon original= new ImageIcon("img\\PACMANLabel.png");
        Editgambar.setIcon(original);
    }//GEN-LAST:event_EditorActionPerformed

    private void CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorActionPerformed
        Base.removeAll();
        Base.repaint();
        Base.revalidate();
        
        Base.add(Calc_panel);
        Base.repaint();
        Base.revalidate();
        time_calc.start();
    }//GEN-LAST:event_CalculatorActionPerformed

    private void BackbuttonEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonEditorActionPerformed
        Base.removeAll();
        Base.repaint();
        Base.revalidate();
        
        Base.add(Welcome);
        Base.repaint();
        Base.revalidate();
        
    }//GEN-LAST:event_BackbuttonEditorActionPerformed

    private void BackbuttonCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonCalcActionPerformed
        Base.removeAll();
        Base.repaint();
        Base.revalidate();
        
        Base.add(Welcome);
        Base.repaint();
        Base.revalidate();
      
    }//GEN-LAST:event_BackbuttonCalcActionPerformed

    private void BackbuttonMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonMediaActionPerformed
        Base.removeAll();
        Base.repaint();
        Base.revalidate();
        
        Base.add(Welcome);
        Base.repaint();
        Base.revalidate();
        
    }//GEN-LAST:event_BackbuttonMediaActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        About_pop_up muncul = new About_pop_up();
        muncul.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private static void resizeImage(File originalImage, File resizedImage, int width, int height, String format) throws IOException{
    try 
    {   
        BufferedImage original = ImageIO.read(originalImage);
        BufferedImage resized = new BufferedImage(width, height, original.getType());
        Graphics2D g2 = resized.createGraphics();
        g2.drawImage(original, 0, 0, width, height, null);
        g2.dispose();
        ImageIO.write(resized, "png", resizedImage);
        
    } catch (Exception e)
        {   
            e.printStackTrace();
        }    
    }
    
    public static final int FLIP_VERTICAL = 1;
    public static final int FLIP_HORIZONTAL = -1;
            
    private static void flip(File Input, File Output, int direction){
        try
        {
            BufferedImage image = ImageIO.read(Input);
            int width = image.getWidth();
            int height = image.getHeight();
            BufferedImage flipped = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            
            for(int y=0;y<height;y++)
            {
                for(int x=0;x<width;x++)
                {
                    switch(direction)
                    {
                        case FLIP_HORIZONTAL:
                            flipped.setRGB((width-1)-x, y, image.getRGB(x,y));
                            break;
                            
                        case FLIP_VERTICAL:
                            flipped.setRGB(x, (height-1)-y, image.getRGB(x, y));
                            break;
                    }
                }
            }
            
            ImageIO.write(flipped, "png", Output);
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERFACE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About;
    private javax.swing.JButton Angka_0;
    private javax.swing.JButton Angka_1;
    private javax.swing.JButton Angka_2;
    private javax.swing.JButton Angka_3;
    private javax.swing.JButton Angka_4;
    private javax.swing.JButton Angka_5;
    private javax.swing.JButton Angka_6;
    private javax.swing.JButton Angka_7;
    private javax.swing.JButton Angka_8;
    private javax.swing.JButton Angka_9;
    private javax.swing.JLabel Animasi;
    private javax.swing.JLabel Animasi_calc;
    private javax.swing.JLabel Animasi_editor;
    private javax.swing.JLabel Animasi_media;
    private javax.swing.JButton BackbuttonCalc;
    private javax.swing.JButton BackbuttonEditor;
    private javax.swing.JButton BackbuttonMedia;
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Calc_panel;
    private javax.swing.JButton Calculator;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Desimal;
    private javax.swing.JButton Disable;
    private javax.swing.JLabel Editgambar;
    private javax.swing.JButton Editor;
    private javax.swing.JPanel Editor_panel;
    private javax.swing.JButton Enable;
    private javax.swing.JButton Flip_Horizontal;
    private javax.swing.JButton Flip_Vertical;
    private javax.swing.JButton Grayscale;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Hasil;
    private javax.swing.JLabel History;
    private javax.swing.JButton Kurang;
    private javax.swing.JButton Media;
    private javax.swing.JPanel Media_panel;
    private javax.swing.JButton Pembagian;
    private javax.swing.JButton Perkalian;
    private javax.swing.JButton Play_Music;
    private javax.swing.JButton Play_Video;
    private javax.swing.JButton Resize;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField Tempat_Angka;
    private javax.swing.JRadioButton Tombol_Off;
    private javax.swing.JRadioButton Tombol_On;
    private javax.swing.JPanel Welcome;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
